# Generated by Django 3.2.23 on 2023-11-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
