# Generated by Django 3.2.23 on 2023-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='done',
        ),
        migrations.AddField(
            model_name='item',
            name='context',
            field=models.TextField(default='Add you review', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
