# Generated by Django 3.2.23 on 2024-02-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_auto_20231113_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='context',
            field=models.TextField(default='Add your review', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Add your name', max_length=30),
        ),
    ]
